### ISSUE TITLE
[Inquiry] Tracking process

### ISSUE THREAD

**Issue by doctorloaf** [opencoconut/coconutrb#1]
Is there any way to track progress through this gem? It looks like in the early evolution of this gem (heywatch), there was a way to fetch the current progress of the encoding.

To be more detailed:

I'm looking to pass back the percentage of completion for the encoding process so that I can pass that value to the client and let them know how far along the encoding process is.

**Comment by brunoceleste** [comment]
You have to use the webhook progress event option `events=true`, see our documentation here http://coconut.co/docs/api/config/webhook
