### ISSUE TITLE
endpoint seems to be wrong

### ISSUE THREAD

**Issue by ConfusedVorlon** [opencoconut/coconutrb#9]
If you don't specify the endpoint manually, then the client forms one like

`https://api-us-west-1.coconut.co/v2`

It seems this is no longer supported

**Comment by brunoceleste** [comment]
Hello,

This region is not supported. That's why it's not working.
Supported regions are: 
us-west-2
eu-west-1

us-east-1 is default so no need to change the region in your code.

**Comment by ConfusedVorlon** [comment]
thanks.
